### ISSUE TITLE
issue in Soil Moisture Mapping

### ISSUE THREAD

**Issue by dhakalsandesh33** [sepal-contrib/sepal_pysmm#34]
dear users, I have linked the GEE assets to SEPAL for selecting the Area of interest. but while running the process my start processing there is the issue of string indices must be integers. what does it mean? how can I resolve this issue? please help me. Attached the screenshot of the issue I have faced. 
![SEPAL](https://user-images.githubusercontent.com/126433738/222059672-4dafa645-7cf5-43ca-be9b-0cd8b8d1d6bb.jpg)

**Comment by dfguerrerom** [comment]
thanks for reporting, the error was fixed.

**Comment by dhakalsandesh33** [comment]
thank you!
